repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: .venv/bin/ruff check --fix
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        entry: .venv/bin/ruff format
        language: system
        types_or: [python, pyi]
      - id: ty-check
        name: ty check
        entry: .venv/bin/ty check
        language: system
        pass_filenames: false
        always_run: true
