[pytest]
addopts = --doctest-modules --cov allocine
filterwarnings =
    ignore:'asyncio\.iscoroutinefunction' is deprecated:DeprecationWarning:backoff\._decorator
    ignore:.*invalid escape sequence:SyntaxWarning
    ignore:"is" with 'int' literal:SyntaxWarning
