# Based on https://gist.github.com/Mathieu-Castets/e36488c518d1fc4a03fa (thank you!)
nationalities = {
    'AD': ('andorran', 'andorrane'),
    'AE': ('émirien', 'émirienne'),
    'AF': ('afghan', 'afghane'),
    'AG': ('antiguayen', 'antiguayenne'),
    'AI': ('anguillais', 'anguillaise'),
    'AL': ('albanais', 'albanaise'),
    'AM': ('arménien', 'arménienne'),
    'AO': ('angolais', 'angolaise'),
    'AR': ('argentin', 'argentine'),
    'AS': ('samoan', 'samoane'),
    'AT': ('autrichien', 'autrichienne'),
    'AU': ('australien', 'australienne'),
    'AW': ('arubain', 'arubaine'),
    'AX': ('ålandais', 'ålandaise'),
    'AZ': ('azerbaïdjanais', 'azerbaïdjanaise'),
    'BA': ('bosnien', 'bosnienne'),
    'BB': ('barbadien', 'barbadienne'),
    'BD': ('bangladais', 'bangladaise'),
    'BE': ('belge', 'belge'),
    'BF': ('burkinabè', 'burkinabè'),
    'BG': ('bulgare', 'bulgare'),
    'BH': ('bahreïnien', 'bahreïnienne'),
    'BI': ('burundais', 'burundaise'),
    'BJ': ('béninois', 'béninoise'),
    'BM': ('bermudien', 'bermudienne'),
    'BN': ('brunéiens', 'brunéiennes'),
    'BO': ('bolivien', 'bolivienne'),
    'BR': ('brésilien', 'brésilienne'),
    'BS': ('bahamien', 'bahamienne'),
    'BT': ('bhoutanais', 'bhoutanaise'),
    'BW': ('botswanais', 'botswanaise'),
    'BY': ('biélorusse', 'biélorusse'),
    'BZ': ('bélizien', 'bélizienne'),
    'CA': ('canadien', 'canadienne'),
    'CD': ('congolais', 'congolaise'),
    'CF': ('centrafricain', 'centrafricaine'),
    'CG': ('congolais', 'congolaise'),
    'CH': ('suisse', 'suissesse'),
    'CI': ('ivoirien', 'ivoirienne'),
    'CK': ('cookien', 'cookienne'),
    'CL': ('chilien', 'chilienne'),
    'CM': ('camerounais', 'camerounaise'),
    'CN': ('chinois', 'chinoise'),
    'CO': ('colombien', 'colombienne'),
    'CR': ('costaricien', 'costaricienne'),
    'CU': ('cubain', 'cubaine'),
    'CV': ('cap-verdien', 'cap-verdienne'),
    'CY': ('chypriote', 'chypriote'),
    'CS': ('tchécoslovaque', 'tchécoslovaque'),
    'CZ': ('tchèque', 'tchèque'),
    'DE': ('allemand', 'allemande'),
    'DJ': ('djiboutien', 'djiboutienne'),
    'DK': ('danois', 'danoise'),
    'DM': ('dominiquais', 'dominiquaise'),
    'DO': ('dominicain', 'dominicaine'),
    'DZ': ('algérien', 'algérienne'),
    'EC': ('équatorien', 'équatorienne'),
    'EE': ('estonien', 'estonienne'),
    'EG': ('égyptien', 'égyptienne'),
    'EH': ('sahraoui', 'sahraouie'),
    'EL': ('grec', 'grecque'),
    'ER': ('érythréen', 'érythréenne'),
    'ES': ('espagnol', 'espagnole'),
    'ET': ('éthiopien', 'éthiopienne'),
    'FI': ('finlandais', 'finlandaise'),
    'FJ': ('fidjien', 'fidjienne'),
    'FK': ('malouin', 'malouine'),
    'FM': ('micronésien', 'micronésienne'),
    'FO': ('féroïen', 'féroïenne'),
    'FR': ('français', 'française'),
    'GA': ('gabonais', 'gabonaise'),
    'GB': ('britannique', 'britannique'),
    'GD': ('grenadin', 'grenadine'),
    'GE': ('géorgien', 'géorgienne'),
    'GH': ('ghanéen', 'ghanéenne'),
    'GI': ('gibraltarien', 'gibraltarienne'),
    'GL': ('groenlandais', 'groenlandaise'),
    'GM': ('gambien', 'gambienne'),
    'GN': ('guinéen', 'guinéenne'),
    'GQ': ('équatoguinéen', 'équatoguinéenne'),
    'GR': ('grec', 'grecque'),
    'GT': ('guatémaltèque', 'guatémaltèque'),
    'GU': ('guamien', 'guamienne'),
    'GW': ('bissaoguinéen', 'bissaoguinéenne'),
    'GY': ('guyanien', 'guyanienne'),
    'HK': ('hongkongais', 'hongkongaise'),
    'HN': ('hondurien', 'hondurienne'),
    'HR': ('croate', 'croate'),
    'HT': ('haïtien', 'haïtienne'),
    'HU': ('hongrois', 'hongroise'),
    'ID': ('indonésien', 'indonésienne'),
    'IE': ('irlandais', 'iirlandaise'),
    'IL': ('israélien', 'israélienne'),
    'IN': ('indien', 'indienne'),
    'IQ': ('iraquien', 'iraquienne'),
    'IR': ('iranien', 'iranienne'),
    'IS': ('islandais', 'islandaise'),
    'IT': ('italien', 'italienne'),
    'JM': ('jamaïcain', 'jamaïcaine'),
    'JO': ('jordanien', 'jordanienne'),
    'JP': ('japonais', 'japonaise'),
    'KE': ('kényan', 'kényane'),
    'KG': ('kirghize', 'kirghize'),
    'KH': ('cambodgien', 'cambodgienne'),
    'KI': ('kiribatien', 'kiribatienne'),
    'KM': ('comorien', 'comorienne'),
    'KN': ('christophien', 'christophienne'),
    'KP': ('nord-coréen', 'nord-coréenne'),
    'KR': ('sud-coréen', 'sud-coréenne'),
    'KW': ('koweïtien', 'koweïtienne'),
    'KY': ('caïmanais', 'caïmanaise'),
    'KZ': ('kazakh', 'kazakhe'),
    'LA': ('laotien', 'laotienne'),
    'LB': ('libanais', 'libanaise'),
    'LC': ('saint-lucien', 'saint-lucienne'),
    'LI': ('liechtensteinois', 'liechtensteinoise'),
    'LK': ('sri-lankais', 'sri-lankaise'),
    'LR': ('libérien', 'libérienne'),
    'LS': ('mosotho', 'mosotho'),
    'LT': ('lituanien', 'lituanienne'),
    'LU': ('luxembourgeois', 'luxembourgeoise'),
    'LV': ('letton', 'lettone'),
    'LY': ('libyen', 'libyenne'),
    'MA': ('marocain', 'marocaine'),
    'MC': ('monégasque', 'monégasque'),
    'MD': ('moldave', 'moldave'),
    'ME': ('monténégrin', 'monténégrine'),
    'MG': ('malgache', 'malgache'),
    'MH': ('marshallais', 'marshallaise'),
    'MK': ('macédonien', 'macédonienne'),
    'ML': ('malien', 'malienne'),
    'MM': ('birman', 'birmane'),
    'MN': ('mongol', 'mongole'),
    'MO': ('macanais', 'macanaise'),
    'MP': ('mariannais', 'mariannaise'),
    'MR': ('mauritanien', 'mauritanienne'),
    'MS': ('montserratien', 'montserratienne'),
    'MT': ('maltais', 'maltaise'),
    'MU': ('mauricien', 'mauricienne'),
    'MV': ('maldivien', 'maldivienne'),
    'MW': ('malawien', 'malawienne'),
    'MX': ('mexicain', 'mexicaine'),
    'MY': ('malaisien', 'malaisienne'),
    'MZ': ('mozambicain', 'mozambicaine'),
    'NA': ('namibien', 'namibienne'),
    'NE': ('nigérien', 'nigérienne'),
    'NG': ('nigérian', 'nigériane'),
    'NI': ('nicaraguayen', 'nicaraguayenne'),
    'NL': ('néerlandais', 'néerlandaise'),
    'NO': ('norvégien', 'norvégienne'),
    'NP': ('népalais', 'népalaise'),
    'NR': ('nauruan', 'nauruane'),
    'NU': ('niuéan', 'niuéane'),
    'NZ': ('néo-zélandais', 'néo-zélandaise'),
    'OM': ('omanais', 'omanaise'),
    'PA': ('panaméen', 'panaméenne'),
    'PE': ('péruvien', 'péruvienne'),
    'PG': ('papouasien', 'papouasienne'),
    'PH': ('philippin', 'philippine'),
    'PK': ('pakistanais', 'pakistanaise'),
    'PL': ('polonais', 'polonaise'),
    'PR': ('portoricain', 'portoricaine'),
    'PS': ('palestinien', 'palestinienne'),
    'PT': ('portugais', 'portugaise'),
    'PW': ('palaois', 'palaoise'),
    'PY': ('paraguayen', 'paraguayenne'),
    'QA': ('qatarien', 'qatarienne'),
    'RO': ('roumain', 'roumaine'),
    'RS': ('serbe', 'serbe'),
    'RU': ('russe', 'russe'),
    'RW': ('rwandais', 'rwandaise'),
    'SA': ('saoudien', 'saoudienne'),
    'SB': ('salomonais', 'salomonaise'),
    'SC': ('seychellois', 'seychelloise'),
    'SD': ('soudanais', 'soudanaise'),
    'SE': ('suédois', 'suédoise'),
    'SG': ('singapourien', 'singapourienne'),
    'SI': ('slovène', 'slovène'),
    'SK': ('slovaque', 'slovaque'),
    'SL': ('sierraléonais', 'sierraléonaise'),
    'SM': ('saint-marinais', 'saint-marinaise'),
    'SN': ('sénégalais', 'sénégalaise'),
    'SO': ('somalien', 'somalienne'),
    'SR': ('surinamais', 'surinamaise'),
    'SS': ('sud-soudanais', 'sud-soudanaise'),
    'ST': ('santoméen', 'santoméenne'),
    'SU': ('soviétique', 'soviétique'),
    'SV': ('salvadorien', 'salvadorienne'),
    'SY': ('syrien', 'syrienne'),
    'SZ': ('swazi', 'swazie'),
    'TC': ('émirats arabes unis', 'émirats arabes unis'),
    'TD': ('tchadien', 'tchadienne'),
    'TG': ('togolais', 'togolaise'),
    'TH': ('thaïlandais', 'thaïlandaise'),
    'TJ': ('tadjik', 'tadjike'),
    'TK': ('tokélaouen', 'tokélaouenne'),
    'TL': ('timorais', 'timoraise'),
    'TM': ('turkmène', 'turkmène'),
    'TN': ('tunisien', 'tunisienne'),
    'TO': ('tongan', 'tongane'),
    'TP': ('est-timorais', 'est-timoraise'),
    'TR': ('turc', 'turque'),
    'TT': ('trinidadien', 'trinidadienne'),
    'TV': ('tuvaluan', 'tuvaluane'),
    'TW': ('taïwanais', 'taïwanaise'),
    'TZ': ('tanzanien', 'tanzanienne'),
    'UA': ('ukrainien', 'ukrainienne'),
    'UG': ('ougandais', 'ougandaise'),
    'UK': ('britannique', 'britannique'),
    'US': ('américain', 'américaine'),
    'UY': ('uruguayen', 'uruguayenne'),
    'UZ': ('ouzbek', 'ouzbèke'),
    'VC': ('vincentais', 'vincentaise'),
    'VE': ('vénézuélien', 'vénézuélienne'),
    'VG': ('insulaires des îles vierges britanniques', 'insulaires des îles vierges britanniques'),
    'VI': ('insulaires des îles vierges', 'insulaires des îles vierges'),
    'VN': ('vietnamien', 'vietnamienne'),
    'VU': ('vanuatuan', 'vanuatuane'),
    'WS': ('samoan', 'samoane'),
    'XK': ('kosovar', 'kosovare'),
    'YE': ('yéménite', 'yéménite'),
    'YU': ('serbe', 'serbe'),
    'ZA': ('sud-africain', 'sud-africaine'),
    'ZM': ('zambien', 'zambienne'),
    'ZW': ('zimbabwéen', 'zimbabwéenne'),
}


countries = {
    'andorre': 'AD',
    'emirats arabes unis': 'AE',
    'afghanistan': 'AF',
    'antigua et barbuda': 'AG',
    'anguilla': 'AI',
    'albanie': 'AL',
    'curacao': 'AN',
    'angola': 'AO',
    'argentine': 'AR',
    'samoa': 'AS',
    'samoa americaines': 'AS',
    'autriche': 'AT',
    'australie': 'AU',
    'aruba': 'AW',
    'azerbaidjan': 'AZ',
    'bosnie-herzegovine': 'BA',
    'barbade': 'BB',
    'bangladesh': 'BD',
    'belgique': 'BE',
    'burkina faso': 'BF',
    'bulgarie': 'BG',
    'bahrein': 'BH',
    'burundi': 'BI',
    'benin': 'BJ',
    'bermudes': 'BM',
    'brunei': 'BN',
    'bolivie': 'BO',
    'bresil': 'BR',
    'bahamas': 'BS',
    'bhoutan': 'BT',
    'botswana': 'BW',
    'bielorussie': 'BY',
    'belize': 'BZ',
    'canada': 'CA',
    'congo rdc': 'CD',
    'republique centrafricaine': 'CF',
    'congo (brazzaville)': 'CG',
    'suisse': 'CH',
    'cote d\'ivoire': 'CI',
    'iles cook': 'CK',
    'chili': 'CL',
    'cameroun': 'CM',
    'chine': 'CN',
    'colombie': 'CO',
    'costa rica': 'CR',
    'cuba': 'CU',
    'cap vert': 'CV',
    'chypre': 'CY',
    'republique tcheque': 'CZ',
    'tchecoslovaquie': 'CS',
    'allemagne': 'DE',
    'allemagne de l\'ouest': 'DE',
    'allemagne de l\'est': 'DE',
    'djibouti': 'DJ',
    'danemark': 'DK',
    'dominique': 'DM',
    'republique dominicaine': 'DO',
    'algerie': 'DZ',
    'equateur': 'EC',
    'estonie': 'EE',
    'egypte': 'EG',
    'erythree': 'ER',
    'espagne': 'ES',
    'ethiopie': 'ET',
    'finlande': 'FI',
    'fidji': 'FJ',
    'iles malouines': 'FK',
    'micronesie': 'FM',
    'france': 'FR',
    'gabon': 'GA',
    'grande-bretagne': 'GB',  # modified based on allocine value, originally 'Royaume-Uni'
    'grenade': 'GD',
    'georgie': 'GE',
    'ghana': 'GH',
    'gibraltar': 'GI',
    'gambie': 'GM',
    'guinee': 'GN',
    'guinee equatoriale': 'GQ',
    'grece': 'GR',
    'guatemala': 'GT',
    'guam': 'GU',
    'guinee-bissau': 'GW',
    'guyana': 'GY',
    'hong kong': 'HK',
    'hong-kong': 'HK',
    'honduras': 'HN',
    'croatie': 'HR',
    'haiti': 'HT',
    'hongrie': 'HU',
    'inde': 'IN',
    'indonesie': 'ID',
    'irak': 'IQ',
    'iran': 'IR',
    'irlande': 'IE',
    'israel': 'IL',
    'islande': 'IS',
    'italie': 'IT',
    'jamaique': 'JM',
    'jordanie': 'JO',
    'japon': 'JP',
    'kenya': 'KE',
    'kyrghyzstan': 'KG',
    'cambodge': 'KH',
    'kiribati': 'KI',
    'comores': 'KM',
    'saint-christophe-et-nieves': 'KN',
    'coree du sud': 'KR',  # modified based on allocine value, originally 'Coree, Republique de'
    'koweit': 'KW',
    'iles caimans': 'KY',
    'kazakhstan': 'KZ',
    'laos': 'LA',
    'liban': 'LB',
    'sainte-lucie': 'LC',
    'liechtenstein': 'LI',
    'sri lanka': 'LK',
    'liberia': 'LR',
    'lesotho': 'LS',
    'lituanie': 'LT',
    'luxembourg': 'LU',
    'lettonie': 'LV',
    'libye': 'LY',
    'maroc': 'MA',
    'monaco': 'MC',
    'moldavie': 'MD',
    'montenegro': 'ME',
    'madagascar': 'MG',
    'iles marshall': 'MH',
    'macedoine': 'MK',
    'mali': 'ML',
    'birmanie': 'MM',
    'mongolie': 'MN',
    'macao': 'MO',
    'iles mariannes du nord': 'MP',
    'mauritanie': 'MR',
    'montserrat': 'MS',
    'malte': 'MT',
    'maurice': 'MU',
    'maldives': 'MV',
    'malawi': 'MW',
    'mexique': 'MX',
    'malaisie': 'MY',
    'mozambique': 'MZ',
    'namibie': 'NA',
    'niger': 'NE',
    'nigeria': 'NG',
    'nicaragua': 'NI',
    'pays-bas': 'NL',
    'norvege': 'NO',
    'nepal': 'NP',
    'nauru': 'NR',
    'nioue': 'NU',
    'nouvelle-zelande': 'NZ',
    'oman': 'OM',
    'panama': 'PA',
    'perou': 'PE',
    'papouasie-nouvelle-guinee': 'PG',
    'philippines': 'PH',
    'pakistan': 'PK',
    'pologne': 'PL',
    'porto rico': 'PR',
    'autorite palestinienne': 'PS',
    'portugal': 'PT',
    'palaos': 'PW',
    'paraguay': 'PY',
    'qatar': 'QA',
    'roumanie': 'RO',
    'russie': 'RU',
    'rwanda': 'RW',
    'arabie saoudite': 'SA',
    'iles salomon': 'SB',
    'soudan': 'SD',
    'suede': 'SE',
    'singapour': 'SG',
    'slovenie': 'SI',
    'slovaquie': 'SK',
    'sierra leone': 'SL',
    'senegal': 'SN',
    'somalie': 'SO',
    'suriname': 'SR',
    'sao tome-et-principe': 'ST',
    'el salvador': 'SV',
    'saint-martin': 'SX',
    'syrie': 'SY',
    'iles turques-et-caiques': 'TC',
    'tchad': 'TD',
    'togo': 'TG',
    'thailande': 'TH',
    'tadjikistan': 'TJ',
    'turkmenistan': 'TM',
    'tunisie': 'TN',
    'tonga': 'TO',
    'timor oriental': 'TP',
    'turquie': 'TR',
    'trinite-et-tobago': 'TT',
    'tuvalu': 'TV',
    'taiwan': 'TW',
    'tanzanie': 'TZ',
    'ukraine': 'UA',
    'ouganda': 'UG',
    'u.r.s.s.': 'SU',
    'u.s.a.': 'US',  # modified based on allocine value, originally 'etats-unis'
    'uruguay': 'UY',
    'ouzbekistan': 'UZ',
    'saint-vincent-et-les grenadines': 'VC',
    'venezuela': 'VE',
    'iles vierges (britanniques)': 'VG',
    'iles vierges': 'VI',
    'vietnam': 'VN',
    'vanuatu': 'VU',
    'samoa occidentales': 'WS',
    'kosovo': 'XK',
    'yemen': 'YE',
    'serbie': 'YU',
    'afrique du sud': 'ZA',
    'zambie': 'ZM',
    'zimbabwe': 'ZW',
}
